[package]
name = "blockbucket"
version = "0.2.7"
edition = "2024"
description = "Read Write Delete (block u8: key, data) to bucket file"
license = "MIT"
repository = "https://github.com/manhavn/blockbucket"

[lib]
path = "src/lib.rs"

[dependencies]
md5 = "0.8.0"
